homework5: driver.o iofunctions.o
	gcc -o homework5 driver.o iofunctions.o

driver.o: driver.c
	gcc -ansi -pedantic-errors -Wall -c driver.c

iofunctions.o: iofunctions.c
	gcc -ansi -pedantic-errors -Wall -c iofunctions.c
