homework10: homework10.o Pokemon.o Torterra.o Mimikyu.o Heracross.o
	g++ -o homework10 homework10.o Pokemon.o Torterra.o Mimikyu.o Heracross.o

homework10.o: homework10.cpp
	g++ -ansi -pedantic-errors -Wall -c homework10.cpp

Pokemon.o: Pokemon.cpp
	g++ -ansi -pedantic-errors -Wall -c Pokemon.cpp

Torterra.o: Torterra.cpp
	g++ -ansi -pedantic-errors -Wall -c Torterra.cpp

Mimikyu.o: Mimikyu.cpp
	g++ -ansi -pedantic-errors -Wall -c Mimikyu.cpp

Heracross.o: Heracross.cpp
	g++ -ansi -pedantic-errors -Wall -c Heracross.cpp
